# $Id: makefile,v 1.3 2005/01/18 19:48:02 wyoung Exp $

# Use the generic AIPS++ script installation makefile.
#-----------------------------------------------------
SCRIPTS := aips++
include $(word 1, $(AIPSPATH))/code/install/makefile.scr
