# $Id: makefile,v 19.1 2004/08/25 00:54:56 cvsmgr Exp $

# Use the generic AIPS++ scripts makefile.
#---------------------------------------------
XLIBLIST=GLISH
include $(word 1, $(AIPSPATH))/code/install/makefile.app

