# $Id: makefile,v 19.1 2004/12/09 16:24:09 wyoung Exp $
XLIBLIST :=  CFITSIO MIRLIB LAPACK F77 GLISH PGPLOT WCSLIB X11
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
