# $Id: makefile,v 1.1 2006/02/07 06:45:37 rassendo Exp $

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

