# $Id: makefile,v 19.1 2004/08/24 23:29:58 cvsmgr Exp $

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
