#!/bin/sh
#-----------------------------------------------------------------------------
# Usage: cubecat
#-----------------------------------------------------------------------------
# Startup script for cubecat - the multibeam cubelet concatenator.
#
# $Id: cubecat,v 19.0 2003/07/16 03:34:57 aips2adm Exp $
#-----------------------------------------------------------------------------
# Check that the DISPLAY variable is set.
  if [ "$DISPLAY" = "" ]
  then
     echo "DISPLAY variable is not set, abort!"
     exit 1
  fi

# Check that AIPSPATH is defined.
  if [ "$AIPSPATH" = "" ]
  then
#    AIPS++ initialization.
     echo "AIPS++ initialization..."
     . /nfs/aips++/stable/aipsinit.sh
  else
#    Make sure that we use the AIPS++ Glish installation.
     AIPSBIN=`echo $AIPSPATH | awk '{print $1"/"$2"/bin"}'`
     PATH=${AIPSBIN}:$PATH
     export PATH
  fi

# Start it.
  glish -l cubecat.g

  exit
