# $Id: makefile,v 19.2 2004/10/08 03:52:07 nkilleen Exp $

XLIBLIST:= MIRLIB GLISH PGPLOT  CFITSIO X11 LAPACK F77 WCSLIB
LINKAPP := tasking graphics images components coordinates lattices fits measures tables scimath casa

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

