# $Id: makefile,v 19.1 2004/08/24 20:15:44 gvandiep Exp $

# Use the generic AIPS++ package makefile.
#-----------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.pkg
