# $Id: makefile,v 1.1 2007/01/25 08:47:48 wbrouw Exp $

XLIBLIST:=GLISH LAPACK F77 WCSLIB

# Source lists.
#--------------
SCRIPTS  := measures_ftp.sh

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

