# $Id: makefile,v 19.0 2003/07/16 03:39:39 aips2adm Exp $

# Use the generic AIPS++ fortran makefile.
#-----------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.ftn
