# $Id: makefile,v 19.2 2004/08/25 05:51:28 gvandiep Exp $

# Use the generic AIPS++ test makefile.
#--------------------------------------
PGPLOTLIBD := /usr/local/lib
PGPLOTLIB  := -lpgplot
XLIBLIST := PGPLOT X11 F77
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
