# $Id: makefile,v 19.2 2004/10/05 07:58:24 gvandiep Exp $

XLIBLIST := GLISH

LINKAPP := tasking tables casa

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

