# $Id: makefile,v 19.0 2003/07/16 04:17:36 aips2adm Exp $

# Use the generic AIPS++ documentation makefile
#----------------------------------------------
export DOCSROOT :=../../..
recipe1:= -split 0 -no_navigation -address 0 -info 0
include $(word 1, $(AIPSPATH))/code/install/makefile.doc

























































