# $Id: makefile,v 19.0 2003/07/16 03:35:39 aips2adm Exp $

XLIBLIST = MIRLIB

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

