# $Id: makefile,v 19.1 2004/08/24 23:39:43 cvsmgr Exp $

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST := LAPACK F77
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
