# $Id: makefile,v 19.0 2003/07/16 06:01:04 aips2adm Exp $
OPT:=2
XLIBLIST := GLISH QT QWT X11
# you must reference both the QWT and QT packages in your local makedefs
# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

