# $Id: makefile,v 19.0 2003/07/16 06:01:06 aips2adm Exp $

# Use the generic AIPS++ applications directory makefile.
#--------------------------------------------------------
OPT := 2
XLIBLIST:=GLISH GSDLIB
include $(word 1, $(AIPSPATH))/code/install/makefile.app
