# $Id: makefile,v 19.4 2004/10/17 14:07:40 bgarwood Exp $

# Use the generic AIPS++ application makefile.
#---------------------------------------------
LINKAPP := nrao tasking ms fits measures tables scimath casa
XLIBLIST := CFITSIO GLISH F77

include $(word 1, $(AIPSPATH))/code/install/makefile.app
