# $Id: makefile,v 1.1 2005/08/05 02:04:55 mwiering Exp $

XLIBLIST := WCSLIB GLISH PGPLOT LAPACK F77 WCSLIB CFITSIO X11

#LINKAPP := tasking msvis ms images components coordinates lattices fits measures tables scimath \
#          casa 

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app
