# $Id: makefile,v 19.0 2003/07/16 06:00:42 aips2adm Exp $

# Use the generic AIPS++ package makefile.
#-----------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.pkg
