# Fundamentals
#-------------
AIPSROOT := $(word 1, $(AIPSPATH))

memos := -split 0 -info 0
102 := -split +1
103 := -split +1
104 := -split +1
105 := -split +1
107 := -split +1
108 := -split +1
109 := -split +1
111 := -split +1
112 := -split +1


# Use the generic AIPS++ documentation makefile
#----------------------------------------------
include $(AIPSROOT)/code/install/makefile.doc
