# $Id: makefile,v 19.2 2004/08/25 05:51:28 gvandiep Exp $

XLIBLIST=F77 
# Use the generic AIPS++ test makefile.
#--------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
