# $Id: makefile,v 19.3 2006/02/23 08:28:38 gvandiep Exp $

XLIBLIST := CFITSIO
LINKAPP := msfits ms fits measures tables scimath casa

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

