# $Id: makefile,v 19.2 2004/10/17 23:50:51 wbrouw Exp $

XLIBLIST := GLISH

LINKAPP := tasking tables measures scimath casa

# Source lists.
#--------------
BINEXECS := measures_ftp.sh

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

