# $Id: makefile,v 1.1 2004/07/08 03:35:18 tmurphy Exp $

# Use the generic AIPS++ scripts makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.scr
