# $Id: makefile,v 19.2 2006/11/13 02:06:18 gvandiep Exp $
EXTRA_C++FLAGS=-fPIC
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
