# $Id: makefile,v 19.2 2004/10/27 17:28:09 gli Exp $
XLIBLIST:=WCSLIB ATM
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
