# $Id: makefile,v 19.1 2004/08/25 01:05:19 cvsmgr Exp $

XLIBLIST:=GLISH LAPACK WCSLIB PGPLOT F77 Motif XPM X11

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

