# $Id: makefile,v 19.1 2004/08/25 00:44:21 cvsmgr Exp $

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
