# $Id: makefile,v 19.1 2004/08/24 20:15:37 gvandiep Exp $

# Use the generic AIPS++ fortran makefile.
#-----------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.ftn
