# $Id: makefile,v 19.1 2005/06/15 18:02:55 cvsmgr Exp $
XLIBLIST:=Motif PGPLOT WCSLIB XPM X11 F77
# Use the generic AIPS++ test makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
