# $Id: makefile,v 1.1 2006/09/18 22:50:11 gvandiep Exp $

XLIBLIST := PYTHON BOOST

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
