# $Id: makefile,v 19.8 2006/01/24 23:54:58 mcalabre Exp $

XLIBLIST := GLISH RPFITS CFITSIO LAPACK F77
XLIBLIST_shared := GLISH RPFITS CFITSIO LAPACK F77

LINKAPP := atnf tasking ms measures tables scimath casa 

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app
