# $Id: makefile,v 1.2 2006/10/17 03:37:27 gvandiep Exp $

XLIBLIST := BOOST PYTHON

LINKAPP := appspython tables casa 

# Use the common AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.appshr
