# $Id: makefile,v 1.1 2006/09/18 04:12:03 gvandiep Exp $

XLIBLIST := PYTHON BOOST

LINKAPP := appspython tables casa 

# Use the common AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.appshr
