# $Id: makefile,v 19.3 2004/08/25 01:02:02 cvsmgr Exp $

XLIBLIST:=GLISH X11

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

