# $Id: makefile,v 19.2 2004/08/25 11:40:08 gvandiep Exp $

XLIBLIST := PGPLOT Motif X11

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
