# $Id: makefile,v 19.0 2003/07/16 06:03:00 aips2adm Exp $

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST := HDS F77
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
