# $Id: makefile,v 19.1 2004/08/25 01:17:56 cvsmgr Exp $

#prerequisites:
#  trial/implement/Lattices/*
#  trial/implement/Functionals/Polynomial.*, Gaussian1D.*
#  trial/implement/Fitting  (perhaps not all of the following)
#     LatticeFit.cc       LinearFit.h         NonLinearFit.cc     
#     LatticeFit.h        LinearFitSVD.cc     NonLinearFit.h
#     LinearFit.cc        LinearFitSVD.h      NonLinearFitLM.cc
#     NonLinearFitLM.h

XLIBLIST := GLISH LAPACK F77

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

