# $Id: makefile,v 1.1 2005/08/23 22:33:42 gli Exp $

XLIBLIST:= GLISH PGPLOT F77 Motif XPM X11
LINKAPP := tasking graphics msvis ms lattices measures tables scimath casa

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

