# $Id: makefile,v 19.2 2004/10/17 16:06:47 bgarwood Exp $

# Use the generic AIPS++ application makefile.
#---------------------------------------------
LINKAPP := casa
XLIBLIST := GLISH 

include $(word 1, $(AIPSPATH))/code/install/makefile.app


