# $Id: makefile,v 19.0 2003/07/16 06:00:56 aips2adm Exp $
OPT := 2
XLIBLIST:= GLISH  DRAMA
# to compile code, you must have the AAO DRAMA package installed and
# referenced in your local makedefs file
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
