#!/bin/sh
#-----------------------------------------------------------------------------
#   Copyright (C) 1996
#   Associated Universities, Inc. Washington DC, USA.
#
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License as published by the Free
#   Software Foundation; either version 2 of the License, or (at your option)
#   any later version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
#   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#   FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
#   more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   675 Massachusetts Ave, Cambridge, MA 02139, USA.
#
#   Correspondence concerning AIPS++ should be addressed as follows:
#          Internet email: aips2-request@nrao.edu.
#          Postal address: AIPS++ Project Office
#                          National Radio Astronomy Observatory
#                          520 Edgemont Road
#                          Charlottesville, VA 22903-2475 USA
#
#   $Id: gtablebrowser,v 19.1 2004/08/25 01:18:19 cvsmgr Exp $
#
#-----------------------------------------------------------------------------
# this shell script will start up the tablebrowser from the unix command
# line.  it's not very useful at the moment because we don't have a mechanism
# to parse a table name from that command line and pass it to glish.
# so the user will be obliged to type
#    browse ('<their table name>')
# into the glish command line which appears.
# this should become more useful in time...
#
# <todo asof="1996/03/11">
#   <li> parse tablename from shell script's command line and pass to
#        the tablebrowser.
#   <li> hide glish interpreter from view
# </todo>

glish -l tablebrowser.g
