# $Id: makefile,v 19.1 2004/08/25 01:18:34 cvsmgr Exp $

# Use the generic AIPS++ test makefile.
#--------------------------------------
EXCLUDE := README
include $(word 1, $(AIPSPATH))/code/install/makefile.scr
