# $Id: makefile,v 19.0 2003/07/16 06:02:53 aips2adm Exp $

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
XLIBLIST := HDS
XLIBLIST_shared := X11 HDS LAPACK
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
