# $Id: makefile,v 19.0 2003/07/16 03:35:48 aips2adm Exp $

XLIBLIST = MIRLIB BIMA GLISH LAPACK F77 WCSLIB

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

