# $Id: makefile,v 19.1 2005/06/15 17:57:54 cvsmgr Exp $
XLIBLIST:=GLISH Motif PGPLOT WCSLIB X11 XPM LAPACK F77 MIRLIB
# Use the generic AIPS++ test makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
