# $Id: makefile,v 19.0 2003/07/16 03:35:23 aips2adm Exp $

XLIBLIST:=GLISH LAPACK F77 WCSLIB

# Source lists.
#--------------

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

