# $Id: makefile,v 19.4 2004/10/17 16:01:17 bgarwood Exp $

XLIBLIST:=GLISH LAPACK WCSLIB F77
LINKAPP := tasking dish ms coordinates fits measures tables scimath casa

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

