# $Id: makefile,v 19.6 2005/05/23 08:54:53 gvandiep Exp $

# Use the generic AIPS++ application makefile.
#---------------------------------------------
XLIBLIST := CFITSIO GLISH WCSLIB LAPACK F77
LINKAPP := tasking dish msfits ms coordinates lattices fits measures tables scimath casa

include $(word 1, $(AIPSPATH))/code/install/makefile.app

