# $Id: makefile,v 19.0 2003/07/16 04:17:43 aips2adm Exp $

# Use the generic AIPS++ documentation makefile.
#-----------------------------------------------
export DOCSROOT :=../../..
imager-ss433 := -split 0
include $(word 1, $(AIPSPATH))/code/install/makefile.doc
