# $Id: makefile,v 19.0 2003/07/16 03:35:56 aips2adm Exp $

# Use the generic AIPS++ package makefile.
#-----------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.pkg

