# Fundamentals
#-------------
AIPSROOT := $(word 1, $(AIPSPATH))
export DOCSROOT := ../../..

bgadass95 := -split +1
dsadass95 := -split +1
psadass95 := -split +1
rcadass95 := -split +1
rgadass95 := -split +1

# Use the generic AIPS++ documentation makefile
#----------------------------------------------
include $(AIPSROOT)/code/install/makefile.doc
