# Fundamentals
#-------------
AIPSROOT := $(word 1, $(AIPSPATH))
export DOCSROOT := ../../..

bgadass93 := -split +1
gvdadass93 := -split +1

# Use the generic AIPS++ documentation makefile
#----------------------------------------------
include $(AIPSROOT)/code/install/makefile.doc
