# $Id: makefile,v 19.0 2003/07/16 06:01:07 aips2adm Exp $

# Use the generic AIPS++ script installation makefile.
#-----------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.scr
