# $Id: makefile,v 19.3 2004/09/29 14:16:03 gvandiep Exp $

XLIBLIST := WCSLIB MIRLIB CFITSIO

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
