# $Id: makefile,v 19.3 2004/08/25 05:51:28 gvandiep Exp $

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST :=LAPACK F77
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
