# $Id: makefile,v 19.1 2004/11/01 17:46:32 wyoung Exp $
XLIBLIST := CFITSIO WCSLIB
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
