# $Id: makefile,v 19.2 2004/09/29 13:17:28 gvandiep Exp $

XLIBLIST := CFITSIO

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
