# $Id: makefile,v 1.2 2006/09/22 04:53:27 gvandiep Exp $

XLIBLIST := PYTHON BOOST

LINKAPP := appspython tables casa 

# Use the common AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.tstshr
