# $Id: makefile,v 19.1 2004/08/24 21:41:23 cvsmgr Exp $

# Use the generic AIPS++ class implementation makefile.
# ------------------------------------------------------
XLIBLIST := WCSLIB 
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
