# $Id: makefile,v 19.3 2004/09/28 06:28:33 mmarquar Exp $

XLIBLIST := MIRLIB GLISH PGPLOT LAPACK F77 WCSLIB CFITSIO X11

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

