# $Id: makefile,v 19.5 2004/09/28 06:54:23 mmarquar Exp $
XLIBLIST:= MIRLIB GLISH LAPACK F77 WCSLIB CFITSIO 
# Source lists.
#--------------

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

