# $Id: makefile,v 1.2 2006/01/05 17:58:09 wyoung Exp $

XLIBLIST:= GLISH PGPLOT F77 Motif XPM X11
LINKAPP := tasking calibration msvis ms graphics lattices tables measures scimath casa

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

