# $Id: makefile,v 19.2 2004/10/17 15:52:43 bgarwood Exp $

LINKAPP = nrao fits measures tables scimath casa
XLIBLIST := CFITSIO

# Use the generic AIPS++ application makefile.
#---------------------------------------------

include $(word 1, $(AIPSPATH))/code/install/makefile.app
