# $Id: makefile,v 19.0 2003/07/16 03:40:39 aips2adm Exp $

XLIBLIST := GLISH

# Use the generic AIPS++ test makefile.
#--------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
