# $Id: makefile,v 1.2 2004/08/24 23:19:35 cvsmgr Exp $

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
