# $Id: makefile,v 19.2 2004/10/17 23:06:29 wbrouw Exp $

XLIBLIST := GLISH

LINKAPP := tasking tables casa

# Source lists.
#--------------

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

