# $Id: makefile,v 19.1 2005/06/15 18:00:47 cvsmgr Exp $
XLIBLIST := PGPLOT WCSLIB 
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
