# $Id: makefile,v 19.1 2004/08/25 01:05:49 cvsmgr Exp $

# Use the generic AIPS++ scripts makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.scr

