# $Id: makefile,v 19.1 2004/03/16 17:54:42 bgarwood Exp $

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST := LAPACK F77
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
