# Fundamentals
#-------------
AIPSROOT := $(word 1, $(AIPSPATH))

bgadass93 := -split +1
gacadass := -split +1
gvdadass93 := -split +1
hjadassIIpap := -split +1
oonski := -split +1
rgadass98 := -split +1 

# Use the generic AIPS++ documentation makefile
#----------------------------------------------
include $(AIPSROOT)/code/install/makefile.doc
