# $Id: makefile,v 19.1 2004/08/25 02:25:12 cvsmgr Exp $

# Use the generic AIPS++ fortran makefile.
#-----------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.ftn
