# $Id: makefile,v 1.2 2005/06/15 18:10:23 cvsmgr Exp $

XLIBLIST:= TCL TK CFITSIO Motif PGPLOT WCSLIB XPM X11 LAPACK F77 GLISH MIRLIB

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

