
# Use the generic AIPS++ documentation makefile.
#-----------------------------------------------
export DOCSROOT := ../../..
SingleDish:= -split 0 -address 0 -info 0
fswitch:= -split 0 -address 0 -info 0
pswitch:= -split 0 -address 0 -info 0
pswitch2:= -split 0 -address 0 -info 0
fswitch_map:= -split 0 -address 0 -info 0
include $(word 1, $(AIPSPATH))/code/install/makefile.doc
