# $Id: makefile,v 1.4 2005/04/05 20:41:34 rurvashi Exp $

XLIBLIST:= GLISH PGPLOT F77 Motif XPM X11
LINKAPP := tasking graphics msvis ms lattices measures tables scimath casa

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

