# $Id: makefile,v 19.0 2003/07/16 03:38:31 aips2adm Exp $

# Use the generic AIPS++ applications makefile.
#----------------------------------------------
XLIBLIST := GLISH WCSLIB LAPACK F77
include $(word 1, $(AIPSPATH))/code/install/makefile.app
