# $Id: makefile,v 1.1 2004/10/11 07:16:21 gvandiep Exp $

# Use the generic AIPS++ package makefile.
#-----------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.pkg
