# $Id: makefile,v 19.0 2003/07/16 06:10:27 aips2adm Exp $

# Use the generic AIPS++ applications directory makefile.
#--------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.aps
