# $Id: makefile,v 19.1 2004/08/24 21:50:48 cvsmgr Exp $

# Use the generic AIPS++ test makefile.
#--------------------------------------

XLIBLIST := WCSLIB LAPACK F77
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
