# $Id: makefile,v 19.0 2003/07/16 06:01:01 aips2adm Exp $

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST := GLISH GSDLIB
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
