# $Id: makefile,v 19.2 2004/10/05 08:00:10 gvandiep Exp $

XLIBLIST := RPFITS CFITSIO F77
XLIBLIST_shared := RPFITS CFITSIO F77

LINKAPP := atnf

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app
