# $Id: makefile,v 19.1 2004/09/29 00:11:45 mmarquar Exp $

XLIBLIST := GLISH WCSLIB CFITSIO LAPACK F77 MIRLIB

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app
