# $Id: makefile,v 1.1 2004/02/01 17:03:18 wyoung Exp $

# Use the generic AIPS++ checkout makefile.
#------------------------------------------
include $(word 1,$(AIPSPATH))/code/install/makefile.chk
