# $Id: makefile,v 19.5 2005/07/08 16:39:08 ddebonis Exp $

XLIBLIST := WCSLIB GLISH

LINKAPP := tasking tables scimath casa

# Source lists.
#--------------

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

