# $Id: makefile,v 19.3 2004/09/28 05:46:27 mmarquar Exp $
XLIBLIST:= MIRLIB GLISH PGPLOT LAPACK F77 WCSLIB CFITSIO IDL Motif XPM X11


# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

