# $Id: makefile,v 19.6 2005/06/10 22:09:25 wyoung Exp $

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST :=MIRLIB CFITSIO LAPACK F77 WCSLIB MPI ATM
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
