# $Id: makefile,v 19.4 2004/12/09 03:45:23 wyoung Exp $

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST := WCSLIB MIRLIB MPI LAPACK CFITSIO F77
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
