# $Id: makefile,v 1.4 2005/01/12 21:37:00 wyoung Exp $

# Use the generic AIPS++ applications directory makefile.
#--------------------------------------------------------
override NODEP := 1
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
