# $Id: makefile,v 19.4 2005/02/14 06:33:36 mcalabre Exp $

XLIBLIST := GLISH CFITSIO

LINKAPP := atnf tasking tables casa

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app
