# $Id: makefile,v 19.6 2004/10/17 16:04:31 bgarwood Exp $
LINKAPP := tasking ms fits measures tables scimath casa
XLIBLIST := CFITSIO GLISH WCSLIB LAPACK F77
# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

