# $Id: makefile,v 19.0 2003/07/16 03:43:05 aips2adm Exp $

# Use the generic AIPS++ scripts makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.scr

