# $Id: makefile,v 19.2 2004/10/08 20:58:24 wyoung Exp $

XLIBLIST:= CFITSIO MIRLIB GLISH PGPLOT LAPACK F77 WCSLIB IDL Motif XPM X11

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

