# $Id: makefile,v 1.1 2006/09/28 05:55:00 mmarquar Exp $

XLIBLIST := PYTHON BOOST

LINKAPP := appspython measures tables scimath casa 

# Use the common AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.appshr
