# $Id: makefile,v 19.0 2003/07/16 06:01:00 aips2adm Exp $
OPT := 2
XLIBLIST:=GLISH QT QWT
#You must have both the Qt and  QWT packages installed and referenced in
#your local makedefs
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
