# $Id: makefile,v 19.1 2004/08/25 01:03:38 cvsmgr Exp $

XLIBLIST:=GLISH LAPACK PGPLOT F77 X11

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

