# $Id: makefile,v 19.0 2003/07/16 06:04:06 aips2adm Exp $

# Use the generic AIPS++ application makefile.
#---------------------------------------------
XLIBLIST := GLISH PGPLOT X11 LAPACK F77
XLIBLIST_shared := GLISH PGPLOT X11 LAPACK F77
include $(word 1, $(AIPSPATH))/code/install/makefile.app

