# $Id: makefile,v 19.2 2005/07/08 16:19:46 ddebonis Exp $

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
XLIBLIST := WCSLIB MPI
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
