# $Id: makefile,v 19.3 2004/12/09 13:03:14 wyoung Exp $

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST := CFITSIO LAPACK F77 WCSLIB MIRLIB
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
