# $Id: makefile,v 19.2 2004/06/23 06:07:50 gvandiep Exp $

XLIBLIST:=GLISH LAPACK F77

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

