# $Id: makefile,v 1.1 2005/02/14 06:39:16 mcalabre Exp $

XLIBLIST := RPFITS CFITSIO F77
XLIBLIST_shared := RPFITS CFITSIO F77

LINKAPP := atnf ms fits measures tables scimath casa

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app
