# Fundamentals
#-------------
AIPSROOT := $(word 1, $(AIPSPATH))

101:= -split 0
103:= -split 0
105:= -split 0
106:= -split 0
107:= -split 0
108:= -split 0
112:= -split 0
115:= -split 0
116:= -split 0
117:= -split 0
118:= -split 0
120:= -split 0

# Use the generic AIPS++ documentation makefile
#----------------------------------------------
include $(AIPSROOT)/code/install/makefile.doc
