# $Id: makefile,v 19.0 2003/07/16 03:36:06 aips2adm Exp $

XLIBLIST := MIRLIB

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp

