# $Id: makefile,v 19.0 2003/07/16 03:44:20 aips2adm Exp $
# Use the generic AIPS++ application makefile.
#---------------------------------------------

include $(word 1, $(AIPSPATH))/code/install/makefile.app
