# $Id: makefile,v 1.1 2006/09/29 06:42:55 mmarquar Exp $

XLIBLIST := PYTHON BOOST

LINKAPP := appspython scimath casa 

# Use the common AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.appshr
