# $Id: makefile,v 19.1 2004/09/03 01:46:44 nkilleen Exp $

# trial/implement code you must checkout and build first:
#   Graphics/*.cc, *.h except for XRT files
#   
# gplot1d requires PGPLOT version 5.1.  This is available at
# ftp.astro.caltech.edu
# PGPLOT written by Tim Pearson, tjp@astro.caltech.edu
# MOTIF driver written by Martin Shepard, mcs@astro.caltech.edu
 
XLIBLIST=XmPGPLOT Motif X11 GLISH F77 PGPLOT

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

