# $Id: makefile,v 19.3 2005/08/30 07:42:41 wbrouw Exp $
XLIBLIST:=WCSLIB PGPLOT TCL Motif X11 XPM
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
