# $Id: makefile,v 19.0 2003/07/16 06:02:03 aips2adm Exp $

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
XLIBLIST := HDS PGPLOT X11
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
