# $Id: makefile,v 19.4 2005/07/11 06:31:29 gvandiep Exp $

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST := WCSLIB LAPACK F77 IDL XPM Morif X11
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
