# $Id: makefile,v 19.4 2004/10/27 17:24:21 gli Exp $

XLIBLIST:=GLISH LAPACK ATM F77 WCSLIB

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

