# $Id: makefile,v 1.2 2006/10/20 06:30:03 mmarquar Exp $

XLIBLIST := BOOST PYTHON

LINKAPP := appspython scimath casa

# Use the common AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.appshr
