# $Id: makefile,v 19.1 2004/08/25 01:54:13 cvsmgr Exp $

XLIBLIST:=

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.scr

