# $Id: makefile,v 19.0 2003/07/16 04:09:41 aips2adm Exp $
# Use the generic AIPS++ documentation makefile.
#-----------------------------------------------
gsedition2 := -split 2 -no_navigation -address 0 -info 0 
include $(word 1, $(AIPSPATH))/code/install/makefile.doc

