
# Use the generic AIPS++ documentation makefile.
#-----------------------------------------------
export DOCSROOT := ../../..
Synthesis:= -split 0 -address 0 -info 0
bimafiller:= -split 0 -address 0 -info 0
fitstoms:= -split 0 -address 0 -info 0
msclean:= -split 0 -address 0 -info 0
vlacont:= -split 0 -address 0 -info 0
mstofits:= -split 0 -address 0 -info 0
include $(word 1, $(AIPSPATH))/code/install/makefile.doc
