# $Id: makefile,v 19.0 2003/07/16 03:37:55 aips2adm Exp $

# Use the generic AIPS++ checkout makefile.
#------------------------------------------
include $(word 1,$(AIPSPATH))/code/install/makefile.chk
