# $Id: makefile,v 1.1 2005/12/07 05:54:11 tcornwel Exp $

XLIBLIST := 

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

