# $Id: makefile,v 19.0 2003/07/16 06:10:41 aips2adm Exp $

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
