# $Id: makefile,v 19.2 2004/08/25 05:51:28 gvandiep Exp $

# Use the generic AIPS++ class implementation makefile
#-----------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
