# $Id: makefile,v 19.2 2005/07/08 16:33:04 ddebonis Exp $
XLIBLIST:=WCSLIB PGPLOT Motif XPM X11
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
