# $Id: makefile,v 19.3 2006/02/13 06:07:42 mcalabre Exp $

XLIBLIST := F77 GLISH

LINKAPP := atnf tasking tables scimath casa

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app
