# $Id: makefile,v 19.0 2003/07/16 04:19:33 aips2adm Exp $

# Use the generic AIPS++ documentation makefile.
#-----------------------------------------------
faqusing := -split 0 -address 0 -info 0
faqabout := -split 0 -address 0 -info 0 
synthesis := -split 0 -address 0 -info 0
faqprog := -split 0 -address 0 -info 0
dish := -split 0 -address 0 -info 0 
include $(word 1, $(AIPSPATH))/code/install/makefile.doc
