# $Id: makefile,v 19.1 2004/08/25 01:07:14 cvsmgr Exp $

# Use the generic AIPS++ application makefile.
#---------------------------------------------
XLIBLIST:=GLISH LAPACK F77 WCSLIB
include $(word 1, $(AIPSPATH))/code/install/makefile.app

