# $Id: makefile,v 1.2 2004/10/25 11:43:48 gvandiep Exp $

XLIBLIST := LAPACK F77

# Use the generic AIPS++ test makefile.
#--------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
