# $Id: makefile,v 19.1 2005/06/15 17:59:19 cvsmgr Exp $
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
XLIBLIST:=PGPLOT WCSLIB
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
