# $Id: makefile,v 19.1 2005/06/15 18:10:52 cvsmgr Exp $

XLIBLIST:=

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.scr

