#!/bin/sh

ROOT=`echo $0 | sed 's,\(.*\)/[^/][^/]*$,\1,'`

if test -z "$ROOT"; then
    ROOT=.
fi

config_guess=$ROOT/config.guess
config_sub=$ROOT/config.sub

if test -z "$ARCH"; then
    if ARCH_GUESS=`$config_guess`; then :
    else
	echo "Sorry, can't even guess what the architecture might be..."
	exit 1
    fi
    if ARCH=`$config_sub $ARCH_GUESS`; then :
    else
	echo "Sorry, can't even guess what the architecture might be..."
	exit 1
    fi
fi

echo $ARCH
exit 0
