# $Id: makefile,v 19.1 2004/08/25 01:18:59 cvsmgr Exp $

XLIBLIST=GLISH

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

