# $Id: makefile,v 19.2 2004/06/23 06:08:45 gvandiep Exp $

# Use the generic AIPS++ application makefile.
#---------------------------------------------
XLIBLIST := GLISH F77
include $(word 1, $(AIPSPATH))/code/install/makefile.app

