# $Id: makefile,v 19.1 2004/08/25 01:56:36 cvsmgr Exp $

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

