# $Id: makefile,v 19.2 2004/12/19 21:56:14 mwiering Exp $

XLIBLIST:=GLISH LAPACK F77 WCSLIB CFITSIO

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

