# $Id: makefile,v 19.2 2004/08/25 01:27:29 cvsmgr Exp $

XLIBLIST:= MIRLIB GLISH PGPLOT LAPACK F77 WCSLIB Motif XPM X11

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

