# $Id: makefile,v 19.0 2003/07/16 06:04:11 aips2adm Exp $

# Use the generic AIPS++ application makefile.
#---------------------------------------------
XLIBLIST := GLISH HDS F77 
XLIBLIST_shared := GLISH X11 HDS LAPACK F77
include $(word 1, $(AIPSPATH))/code/install/makefile.app

