# $Id: makefile,v 19.0 2003/07/16 06:03:49 aips2adm Exp $

# Use the generic AIPS++ application makefile.
#---------------------------------------------
XLIBLIST := PGPLOT GLISH HDS F77 X11
XLIBLIST_shared := PGPLOT GLISH HDS LAPACK F77 X11
include $(word 1, $(AIPSPATH))/code/install/makefile.app

