# $Id: makefile,v 19.1 2004/08/24 22:01:37 cvsmgr Exp $
XLIBLIST:=X11
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
