# $Id: makefile,v 19.0 2003/07/16 06:10:30 aips2adm Exp $

# Use the generic AIPS++ application makefile.
#---------------------------------------------
XLIBLIST := GLISH
include $(word 1, $(AIPSPATH))/code/install/makefile.app

