# $Id: makefile,v 1.2 2006/02/23 08:32:10 rassendo Exp $

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

