# $Id: makefile,v 19.0 2003/07/16 04:25:36 aips2adm Exp $

# Use the generic AIPS++ documentation makefile.
#-----------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.doc
