
# Use the generic AIPS++ documentation makefile.
#-----------------------------------------------
export DOCSROOT := ../../..
RGeneral:= -split 0 -address 0 -info 0
fftrec:= -split 0 -address 0 -info 0
linfitrec:= -split 0 -address 0 -info 0
measrec:= -split 0 -address 0 -info 0
plotrec:= -split 0 -address 0 -info 0
polyfitrec:= -split 0 -address 0 -info 0
quantrec:= -split 0 -address 0 -info 0
randstatrec:= -split 0 -address 0 -info 0
include $(word 1, $(AIPSPATH))/code/install/makefile.doc
