# $Id: makefile,v 19.2 2004/09/24 21:31:30 gli Exp $
XLIBLIST  := CFITSIO
# Use the generic AIPS++ test makefile.
#--------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
