# $Id: makefile,v 19.4 2004/10/17 23:44:55 wbrouw Exp $

XLIBLIST := GLISH

LINKAPP := tasking tables scimath casa

# Source lists.
#--------------

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

