# $Id: makefile,v 19.4 2006/07/27 04:41:12 mcalabre Exp $

# Use the generic AIPS++ package makefile.
#-----------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.pkg
