# $Id: makefile,v 19.1 2005/06/15 18:09:36 cvsmgr Exp $

XLIBLIST:=GLISH LAPACK F77 WCSLIB

# Source lists.
#--------------

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

