# $Id: makefile,v 19.1 2004/08/25 00:43:25 cvsmgr Exp $
XLIBLIST := GLISH X11
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
