# $Id: makefile,v 19.0 2003/07/16 04:14:28 aips2adm Exp $

# Use the generic AIPS++ documentation makefile
#----------------------------------------------
aprilnews := -split 0 -no_navigation -address 0 -info 0
include $(word 1, $(AIPSPATH))/code/install/makefile.doc



































