# $Id: makefile,v 19.2 2005/06/15 18:01:32 cvsmgr Exp $

XLIBLIST := TCL TK CFITSIO Motif PGPLOT WCSLIB XPM X11 LAPACK F77 GLISH MIRLIB

# Use the generic AIPS++ test makefile.
#--------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
