# $Id: makefile,v 1.2 2004/08/25 02:16:05 cvsmgr Exp $

# Use the generic AIPS++ script installation makefile.
#-----------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.scr
