# $Id: makefile,v 19.1 2004/08/25 01:08:09 cvsmgr Exp $

XLIBLIST:= MIRLIB PGPLOT WCSLIB LAPACK F77 GLISH IDL Motif XPM X11

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

