#!/bin/sh

../bin/clean -nosvcs vis="ngc5921_src.split.ms" alg="hogbom" model="n5921.model" mode="channel" nchan=46 start=1 width=1 step=1 cell=15,15 fieldid=1  imsize=256,256 niter=6000 threshold=0.008
