#!/bin/sh

../bin/mosaic -nosvcs vis="n4826_both.ms" alg="mfclark" model="n4826.model" residual="n4826.resid" image="n4826.im" mode="channel" nchan=30 start=47 width=1 step=4 cell=1,1 spwid=1,2,3 fieldid=1,2,3,4,5,6,7 imsize=256,256
