# $Id: makefile,v 19.0 2003/07/16 06:03:20 aips2adm Exp $

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
XLIBLIST := PGPLOT X11
XLIBLIST_shared := PGPLOT X11 LAPACK
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
