# $Id: makefile,v 19.1 2004/09/29 12:06:06 wyoung Exp $

XLIBLIST := CFITSIO GLISH

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

