# $Id: makefile,v 19.0 2003/07/16 04:17:39 aips2adm Exp $

# Use the generic AIPS++ documentation makefile.
#-----------------------------------------------
export DOCSROOT := ../../..
recipe2:= -split 0 -address 0 -info 0
include $(word 1, $(AIPSPATH))/code/install/makefile.doc
