# $Id: makefile,v 19.2 2005/07/08 16:30:48 ddebonis Exp $
XLIBLIST:=WCSLIB
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
