# $Id: makefile,v 19.3 2006/10/31 04:58:00 gvandiep Exp $
XLIBLIST := CFITSIO
LINKAPP  := ms fits measures tables scimath casa
# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

