# $Id: makefile,v 19.2 2004/10/17 16:05:36 bgarwood Exp $

# Use the generic AIPS++ application makefile.
#---------------------------------------------
LINKAPP := tasking casa
XLIBLIST := GLISH 

include $(word 1, $(AIPSPATH))/code/install/makefile.app

