# $Id: makefile,v 19.3 2004/08/26 08:13:01 gvandiep Exp $

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST := LAPACK F77 IDL XPM Motif X11
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
