# $Id: makefile,v 19.2 2005/06/15 18:08:52 cvsmgr Exp $

# Use the generic AIPS++ applications directory makefile.
#--------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.aps
