# $Id: makefile,v 19.1 2005/06/15 13:40:17 cvsmgr Exp $

# Use the generic AIPS++ application makefile.
#---------------------------------------------
XLIBLIST := GLISH HDS F77
XLIBLIST_shared := GLISH X11 HDS LAPACK F77
include $(word 1, $(AIPSPATH))/code/install/makefile.app

