# $Id: makefile,v 19.2 2004/10/05 08:00:10 gvandiep Exp $

XLIBLIST := F77 GLISH

LINKAPP := atnf tasking measures lattices tables scimath casa

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app
