# $Id: makefile,v 1.1 2005/09/15 05:37:21 tcornwel Exp $

XLIBLIST:=

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.scr

