# $Id: makefile,v 19.1 2004/08/25 01:34:21 cvsmgr Exp $

XLIBLIST:=GLISH LAPACK F77 WCSLIB 

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

