# $Id: makefile,v 19.4 2004/09/27 17:32:41 wyoung Exp $

XLIBLIST := GLISH CFITSIO

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

