# $Id: makefile,v 1.1 2005/05/23 07:31:29 gvandiep Exp $

XLIBLIST := CFITSIO LAPACK F77

# Use the generic AIPS++ test makefile.
#--------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
