# $Id: makefile,v 19.0 2003/07/16 04:14:38 aips2adm Exp $

# Use the generic AIPS++ documentation makefile
#----------------------------------------------
junenews := -split 0 -no_navigation -address 0 -info 0
newsjune := -split +1
include $(word 1, $(AIPSPATH))/code/install/makefile.doc



































