# $Id: makefile,v 19.1 2004/08/25 00:04:50 cvsmgr Exp $
XLIBLIST := WCSLIB
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
