# $Id: makefile,v 19.1 2004/08/24 23:47:38 cvsmgr Exp $
XLIBLIST:=IDL
# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
