# $Id: makefile,v 19.1 2004/08/25 00:44:57 cvsmgr Exp $

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST := GLISH
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
