# $Id: makefile,v 19.4 2006/01/09 22:13:43 tcornwel Exp $

#XLIBLIST:= GLISH PGPLOT F77 Motif XPM X11
#LINKAPP := tasking graphics msvis ms lattices measures tables scimath casa

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.scr

