# $Id: makefile,v 19.0 2003/07/16 03:45:02 aips2adm Exp $

XLIBLIST:=

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.scr

