# $Id: makefile,v 19.1 2004/09/30 05:49:32 gvandiep Exp $

XLIBLIST := CFITSIO

# Use the generic AIPS++ class implementation makefile.
#------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.imp
