# $Id: makefile,v 19.0 2003/07/16 06:10:51 aips2adm Exp $
XLIBLIST = XERCES
#EXTRA_C++FLAGS += -Wall -Wno-comment

# Use the generic AIPS++ applications directory makefile.
#--------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app
# If this line is uncommented, the templates file is not needed.
#C++FLAGS := $(filter-out -fno-implicit-templates, $(C++FLAGS))
#C++FLAGS := $(filter-out -w, $(C++FLAGS))
