# $Id: makefile,v 19.3 2004/10/17 16:02:08 bgarwood Exp $
XLIBLIST := CFITSIO
LINKAPP:=fits casa
# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

