# $Id: makefile,v 19.0 2003/07/16 03:38:40 aips2adm Exp $

XLIBLIST:=GLISH LAPACK F77

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

