# $Id: makefile,v 19.1 2004/08/25 01:46:30 cvsmgr Exp $

XLIBLIST=PGPLOT X11 F77

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

