# $Id: makefile,v 1.1 2006/09/18 04:12:03 gvandiep Exp $

# Use the generic AIPS++ applications directory makefile.
#--------------------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.aps
