# $Id: makefile,v 1.1 2007/01/29 04:20:53 mmarquar Exp $

XLIBLIST_shared := WCSLIB LAPACK BOOST PYTHON F77
LINKAPP := appspython synthesis calibration images lattices components coordinates msvis  ms measures tables scimath fits casa

# Use the common AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.appshr
