# $Id: makefile,v 19.0 2003/07/16 04:17:53 aips2adm Exp $

# Use the generic AIPS++ documentation makefile.
#-----------------------------------------------
export DOCSROOT :=../../..
multifield := -split 0 -info 0 -address 0
include $(word 1, $(AIPSPATH))/code/install/makefile.doc
