# $Id: makefile,v 19.0 2003/07/16 03:42:32 aips2adm Exp $

XLIBLIST=GLISH

# Use the generic AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.app

