# $Id: makefile,v 1.1 2006/09/27 05:46:45 mmarquar Exp $

XLIBLIST := PYTHON BOOST

LINKAPP := appspython tables casa 

# Use the common AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.appshr
