# $Id: makefile,v 1.3 2006/10/19 01:03:05 mmarquar Exp $

XLIBLIST := BOOST PYTHON

LINKAPP := appspython casa 

# Use the common AIPS++ application makefile.
#---------------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.appshr
