# $Id: makefile,v 1.1 2005/05/23 07:38:13 gvandiep Exp $

# Use the generic AIPS++ package makefile.
#-----------------------------------------
include $(word 1, $(AIPSPATH))/code/install/makefile.pkg
