# $Id: makefile,v 19.0 2003/07/16 03:33:46 aips2adm Exp $

# Use the generic AIPS++ test makefile.
#--------------------------------------
XLIBLIST := LAPACK F77 GLISH
include $(word 1, $(AIPSPATH))/code/install/makefile.tst
